spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/auth-service?createDatabaseIfNotExist=yes
    username: root
    password: dave55

server:
  context-path: /uaa
  port: 5000

liquibase:
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}